-- Create a user and schema to hold the Isochron framework objects.
-- Replace 'your_password' with a secure password.
CREATE USER isochron IDENTIFIED BY your_password;
ALTER USER isochron QUOTA UNLIMITED ON users;
GRANT CREATE SESSION, CREATE TABLE, CREATE PROCEDURE, CREATE SEQUENCE, CREATE TRIGGER TO isochron;

-- Control table to store execution information of stored procedures
CREATE TABLE isochron.sp_execution_log(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    procedure_name VARCHAR2(255) NOT NULL,
    parameters CLOB,
    start_time TIMESTAMP WITH TIME ZONE NOT NULL,
    end_time TIMESTAMP WITH TIME ZONE,
    execution_time_ms NUMBER,
    status VARCHAR2(10) NOT NULL CHECK (status IN ('running', 'success', 'failed')),
    log_entry CLOB,
    log_date DATE NOT NULL,
    CONSTRAINT pk_sp_execution_log PRIMARY KEY (id, log_date),
    CONSTRAINT ensure_json CHECK (parameters IS JSON)
)
PARTITION BY RANGE (log_date)
(
  PARTITION p_initial VALUES LESS THAN (TO_DATE('2023-01-01', 'YYYY-MM-DD'))
);

CREATE INDEX idx_procedure_name_start_time ON isochron.sp_execution_log (procedure_name, start_time, log_date);

-- Note on Partitioning in Oracle:
-- Oracle does not have a direct equivalent to PostgreSQL's partman for automatic partition creation.
-- Partition management in Oracle is typically handled by a scheduled database job (e.g., using DBMS_SCHEDULER)
-- that runs a procedure to create new partitions as needed.

-- Example of a procedure to add a new partition for the next day:
CREATE OR REPLACE PROCEDURE isochron.add_daily_partition
IS
    v_today DATE := SYSDATE;
    v_partition_name VARCHAR2(30);
    v_partition_date_str VARCHAR2(10);
    v_high_value_date DATE;
BEGIN
    -- Calculate the date for the new partition (e.g., tomorrow)
    v_high_value_date := TRUNC(v_today) + INTERVAL '2' DAY;
    v_partition_date_str := TO_CHAR(v_high_value_date, 'YYYY_MM_DD');
    v_partition_name := 'P_' || v_partition_date_str;

    -- Check if the partition already exists
    DECLARE
        v_count INTEGER;
    BEGIN
        SELECT COUNT(*)
        INTO v_count
        FROM all_tab_partitions
        WHERE table_owner = 'ISOCHRON'
          AND table_name = 'SP_EXECUTION_LOG'
          AND partition_name = v_partition_name;

        IF v_count = 0 THEN
            -- Add the new partition
            EXECUTE IMMEDIATE 'ALTER TABLE isochron.sp_execution_log ADD PARTITION ' || v_partition_name ||
                              ' VALUES LESS THAN (TO_DATE(''' || TO_CHAR(v_high_value_date, 'YYYY-MM-DD') ||
                              ''', ''YYYY-MM-DD''))';
            DBMS_OUTPUT.PUT_LINE('Partition ' || v_partition_name || ' created.');
        ELSE
            DBMS_OUTPUT.PUT_LINE('Partition ' || v_partition_name || ' already exists.');
        END IF;
    END;
END;
/
